apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod 
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "simonkolz11@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod 
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z060718917OMF6Y7K0ZKU
          region: eu-west-2
      selector: 
        dnsZones:
        - "kolz.link"
    - http01: 
        ingress:
          class: nginx 

