grafana:
  enabled: true

  adminUser: admin
  adminPassword: "ChangeMe123!"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana.kolz.link

    path: /
    pathType: Prefix

    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

prometheus:
  prometheusSpec:
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 2Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true