grafana:
  enabled: true
  adminUser: admin

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.kolz.link
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

prometheus:
  enabled: true
  prometheusSpec:
    retention: 15d

    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 2Gi

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true