apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-app-hub
  labels:
    app: the-app-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: the-app-hub
  template:
    metadata:
      labels:
        app: the-app-hub
    spec:
      containers:
        - name: the-app-hub
          image: moabukar/the-app-hub:22e0324
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
spec:
  type: ClusterIP
  selector:
    app: the-app-hub
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-app-hub
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "the-app-hub.kolz.link"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - the-app-hub.kolz.link
      secretName: the-app-hub-tls
  rules:
    - host: the-app-hub.kolz.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-app-hub
                port:
                  number: 80
